version: "2"
services:
    appcivist-pb-client:
      build:
          context: .
          dockerfile: Dockerfile-dev
      ports:
        - "8000:8000"
      volumes:
      - .:/appcivist-pb-client
      stdin_open: true
      networks:
      - default
networks:
  default:
    external:
      name:  appcivistplatform_default
